# Generated by Django 4.0.3 on 2022-03-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekcorderserverapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trekcorderuser',
            old_name='username',
            new_name='bio',
        ),
    ]
