# Generated by Django 4.0.3 on 2022-03-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekcorderserverapi', '0003_remove_trekcorderuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('uid', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
